# Generated by Django 3.2.5 on 2023-03-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, null=True)),
                ('category', models.CharField(max_length=25, null=True)),
                ('img_url', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.FloatField(null=True)),
                ('stock_amt', models.IntegerField(null=True)),
                ('brand', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
